"""Render the Microsoft Purview vault pack (and NotebookLM exports) into themed HTML pages under library/.

Source of truth stays in Obsidian. Re-run after editing the vault:  python scripts/build_library.py
Writes library/*.html and library/manifest.json (read by index.html's Library view).
"""
import csv
import html
import io
import json
import re
from pathlib import Path

import markdown
import yaml

SITE = Path(__file__).resolve().parent.parent
LIB = SITE / "library"
PACK = Path(r"C:\obsidian\personal_research_2026\Learning\tech-deep-dive\microsoft-purview")
EXP = PACK / "notebooklm" / "exports"

NBLM_CAVEAT = (
    "Generated by NotebookLM from the 36-row Microsoft source ledger. The vault views are the source of truth "
    "where they differ. Known corrections: the GCC FedRAMP \"Moderate vs High\" conflict is resolved by [S35] "
    "(Moderate P-ATO plus High equivalency, not a documentation error); the Amazon S3/RDS gap applies to the "
    "Azure Government Data Map [S4], not to the GCC High or DoD Microsoft 365 columns; claims cited only to "
    "\"Video Transcript\" are not in the ledger."
)

# (slug, source path, section, title override or None, nblm?)
PAGES = [
    ("mission", PACK / "MISSION.md", "Plan", None, False),
    ("day-plan", PACK / "day-plan.md", "Plan", None, False),
    ("mindmap", PACK / "intake" / "mindmap.md", "Plan", "Mind map (scope)", False),
    ("view-01-conceptual", PACK / "views" / "01 - Conceptual View.md", "Architecture views", None, False),
    ("view-02-logical", PACK / "views" / "02 - Logical View.md", "Architecture views", None, False),
    ("view-03-physical", PACK / "views" / "03 - Physical View.md", "Architecture views", None, False),
    ("view-04-integration-ai", PACK / "views" / "04 - Integration and AI Elements.md", "Architecture views", None, False),
    ("diagram-index", PACK / "assets" / "diagrams" / "00 - Diagram Index.md", "Architecture views", "Diagram index", False),
    *[(f"block-{p.stem}", p, "Day blocks", None, False) for p in sorted((PACK / "blocks").glob("*.md"))],
    ("glossary", PACK / "GLOSSARY.md", "Reference", None, False),
    ("cheatsheet", PACK / "reference" / "cheatsheet.md", "Reference", None, False),
    ("quiz-bank", PACK / "reference" / "quiz-bank.md", "Reference", None, False),
    ("source-ledger", PACK / "reference" / "source-ledger.md", "Reference", None, False),
    ("resources", PACK / "RESOURCES.md", "Reference", None, False),
    ("prompt-library", PACK / "prompts" / "00 - Prompt Library.md", "Prompts", None, False),
    ("prompts-tailored", PACK / "prompts" / "tailored-prompts.md", "Prompts", None, False),
    ("prompts-notebooklm-set", PACK / "prompts" / "notebooklm-prompt-set.md", "Prompts", None, False),
    ("prompts-decision-packet", PACK / "prompts" / "notebooklm-room-craft-decision-packet.md", "Prompts", None, False),
    ("prompts-deep-dive-extra", PACK / "prompts" / "deep-dive-extra-prompts.md", "Prompts", None, False),
    ("nblm-briefing", EXP / "Comprehensive Briefing Document_ Microsoft Purview Architecture, Security Contro.md", "NotebookLM reports", "Briefing document", True),
    ("nblm-study-guide", EXP / "Microsoft Purview Technical Study Guide.md", "NotebookLM reports", "Technical study guide", True),
    ("nblm-conceptual", EXP / "Conceptual Architecture View_ Enterprise Data Security, Governance, and AI Prote.md", "NotebookLM reports", "Conceptual architecture view (report)", True),
    ("nblm-logical", EXP / "Logical Architecture View_ Microsoft Purview.md", "NotebookLM reports", "Logical architecture view (report)", True),
    ("nblm-physical", EXP / "Physical Architecture View_ Microsoft Purview Infrastructure, Runtimes, and Clou.md", "NotebookLM reports", "Physical architecture view (report)", True),
    ("nblm-ai-report", EXP / "Technical Report_ Microsoft Purview AI Capabilities, Governance Architecture, an.md", "NotebookLM reports", "AI capabilities technical report", True),
    ("nblm-third-party", EXP / "Catalog of Third-Party and External System Integrations for Microsoft Purview.md", "NotebookLM reports", "Third-party integration catalog", True),
    ("nblm-failure-modes", EXP / "Comprehensive Failure Mode and Security Weakness Catalog for Microsoft Purview D.md", "NotebookLM reports", "Failure mode and security weakness catalog", True),
    ("nblm-crosswalk", EXP / "MICROSOFT PURVIEW ARCHITECTURAL CROSSWALK_ TOGAF ADM, DoDAF VIEWPOINTS, AND ABST.md", "NotebookLM reports", "TOGAF / DoDAF crosswalk", True),
    ("nblm-decision-packet", EXP / "Executive Decision Packet_ Microsoft Purview Architecture & Investment Strategy.md", "NotebookLM reports", "Executive decision packet", True),
    ("nblm-key-claims", EXP / "Key Claims and Architectural Implications of Microsoft Purview.csv", "NotebookLM reports", "Key claims and architectural implications", True),
    ("nblm-mindmap", EXP / "Microsoft Purview Architecture.json", "NotebookLM reports", "NotebookLM mind map", True),
]


def load_sources():
    rows = {}
    text = (PACK / "reference" / "source-ledger.md").read_text(encoding="utf-8")
    for m in re.finditer(r"^\|\s*(\d+)\s*\|\s*([^|]+?)\s*\|\s*(https?://\S+?)\s*\|", text, re.M):
        rows[int(m.group(1))] = (m.group(2), m.group(3))
    return rows


SOURCES = load_sources()


def split_frontmatter(text):
    text = text.lstrip("\ufeff")
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            try:
                fm = yaml.safe_load(text[3:end]) or {}
            except yaml.YAMLError:
                fm = {}
            return fm, text[end + 4:]
    return {}, text


def slug_for_target(target):
    t = target.split("|")[0].split("#")[0].strip().replace("\\", "/")
    name = t.rsplit("/", 1)[-1].removesuffix(".md")
    for slug, path, *_ in PAGES:
        if path.stem == name:
            return slug
    return None


def convert_obsidian(md):
    md = re.sub(r"\$\[(S[^\]]+)\]\$", r"[\1]", md)  # NotebookLM $[S1]$ citations

    def embed(m):
        target = m.group(1).split("|")[0].strip()
        if target.lower().endswith((".png", ".jpg", ".jpeg", ".gif", ".svg")):
            name = target.rsplit("/", 1)[-1]
            sub = "diagrams" if "diagrams" in target else "slides"
            return f'<a href="../assets/{sub}/{name}" target="_blank"><img class="embed" src="../assets/{sub}/{name}" alt="{html.escape(name)}"></a>'
        return ""
    md = re.sub(r"!\[\[([^\]]+)\]\]", embed, md)

    def wikilink(m):
        inner = m.group(1).replace("\\|", "|")
        label = inner.split("|", 1)[1] if "|" in inner else inner.split("/")[-1].removesuffix(".md")
        slug = slug_for_target(inner)
        return f"[{label}]({slug}.html)" if slug else f"*{label}*"
    md = re.sub(r"\[\[([^\]]+)\]\]", wikilink, md)

    # Obsidian callouts -> html blocks
    out, lines, i = [], md.split("\n"), 0
    while i < len(lines):
        m = re.match(r"^>\s*\[!(\w+)\]([-+]?)\s*(.*)$", lines[i])
        if m:
            kind, title = m.group(1).lower(), m.group(3) or m.group(1).title()
            body = []
            i += 1
            while i < len(lines) and lines[i].startswith(">"):
                body.append(re.sub(r"^>\s?", "", lines[i]))
                i += 1
            inner = markdown.markdown("\n".join(body), extensions=["tables", "fenced_code", "sane_lists"])
            out.append(f'<div class="callout {kind}" markdown="0"><div class="callout-title">{html.escape(title)}</div>{inner}</div>\n')
            continue
        out.append(lines[i])
        i += 1
    return "\n".join(out)


def link_citations(h):
    def one(sid):
        n = int(sid[1:])
        if n in SOURCES:
            t, u = SOURCES[n]
            return f'<a class="cite" href="{html.escape(u)}" target="_blank" rel="noopener" title="{html.escape(t)}">{sid}</a>'
        return sid

    def repl(m):
        parts = re.split(r"(\s*,\s*)", m.group(1))
        return "[" + "".join(one(p) if re.fullmatch(r"S\d+", p) else p for p in parts) + "]"
    return re.sub(r"\[((?:S\d+)(?:\s*,\s*S\d+)*)\]", repl, h)


def render_md(text):
    fm, body = split_frontmatter(text)
    body = re.sub(r"^\*\*Location:\*\*.*$", "", body, flags=re.M)
    body = convert_obsidian(body)
    body = re.sub(r"```mermaid\n(.*?)```", lambda m: f'<pre class="mermaid">{html.escape(m.group(1))}</pre>', body, flags=re.S)
    h = markdown.markdown(body, extensions=["tables", "fenced_code", "sane_lists", "md_in_html"])
    h = re.sub(r"<li>\[ \]", '<li class="task"><input type="checkbox" disabled>', h)
    h = re.sub(r"<li>\[x\]", '<li class="task"><input type="checkbox" checked disabled>', h)
    return fm, link_citations(h)


def render_csv(text):
    rows = list(csv.reader(io.StringIO(text.lstrip("\ufeff"))))
    head, body = rows[0], rows[1:]
    t = "<table><thead><tr>" + "".join(f"<th>{html.escape(c)}</th>" for c in head) + "</tr></thead><tbody>"
    for r in body:
        t += "<tr>" + "".join(f"<td>{html.escape(c)}</td>" for c in r) + "</tr>"
    return {}, t + "</tbody></table>"


def render_mindmap_json(text):
    data = json.loads(text.lstrip("\ufeff"))

    def node(n):
        name = html.escape(n.get("name") or n.get("title") or n.get("text") or "")
        kids = n.get("children") or []
        return f"<li>{name}" + (("<ul>" + "".join(node(k) for k in kids) + "</ul>") if kids else "") + "</li>"
    roots = data if isinstance(data, list) else [data]
    return {}, '<ul class="tree">' + "".join(node(r) for r in roots) + "</ul>"


PAGE_TMPL = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title} | Learn Purview</title>
<meta name="description" content="{desc}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="library.css">
<script>try{{var p=JSON.parse(localStorage.getItem("appPalette"))||"github",m=JSON.parse(localStorage.getItem("appMode"))||"dark";document.documentElement.setAttribute("data-theme",p+"-"+m);}}catch(e){{document.documentElement.setAttribute("data-theme","github-dark");}}</script>
</head>
<body>
<header class="topbar">
  <a href="../index.html" class="home">&larr; Learn Purview console</a>
  <span class="crumb">Library · {section}</span>
  <a href="index.html" class="home">All pages</a>
</header>
<main class="doc">
  <div class="kicker">{section}</div>
  <h1 class="doctitle">{title}</h1>
  {descblock}
  {caveat}
  <article>{body}</article>
  <footer class="docfoot">
    Rendered from <code>{source}</code> in the Obsidian vault (source of truth). Study material only. Citations <span class="cite">S#</span> link to the Microsoft source ledger.
    {prevnext}
  </footer>
</main>
<script type="module">
import mermaid from "https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs";
const dark=(document.documentElement.getAttribute("data-theme")||"").endsWith("dark");
mermaid.initialize({{startOnLoad:true,theme:dark?"dark":"default",securityLevel:"strict"}});
</script>
</body>
</html>
"""


def main():
    LIB.mkdir(exist_ok=True)
    manifest = []
    for idx, (slug, path, section, title, nblm) in enumerate(PAGES):
        text = path.read_text(encoding="utf-8")
        if path.suffix == ".csv":
            fm, body = render_csv(text)
        elif path.suffix == ".json":
            fm, body = render_mindmap_json(text)
        else:
            fm, body = render_md(text)
        h1 = re.search(r"<h1>(.*?)</h1>", body)
        page_title = title or (re.sub("<.*?>", "", h1.group(1)) if h1 else path.stem)
        if h1 and not title:
            body = body.replace(h1.group(0), "", 1)
        desc = str(fm.get("description", "")) if fm else ""
        caveat = f'<div class="callout warning"><div class="callout-title">NotebookLM output — read with the vault views</div><p>{link_citations(html.escape(NBLM_CAVEAT))}</p></div>' if nblm else ""
        prev_ = PAGES[idx - 1] if idx > 0 and PAGES[idx - 1][2] == section else None
        next_ = PAGES[idx + 1] if idx + 1 < len(PAGES) and PAGES[idx + 1][2] == section else None
        pn = ""
        if prev_ or next_:
            pn = '<div class="prevnext">' + (f'<a href="{prev_[0]}.html">&larr; Previous</a>' if prev_ else "<span></span>") + \
                 (f'<a href="{next_[0]}.html">Next &rarr;</a>' if next_ else "<span></span>") + "</div>"
        src_rel = str(path.relative_to(PACK.parent.parent.parent)) if PACK.parent.parent.parent in path.parents else path.name
        (LIB / f"{slug}.html").write_text(PAGE_TMPL.format(
            title=html.escape(page_title), desc=html.escape(desc), section=html.escape(section),
            descblock=f'<p class="lead">{html.escape(desc)}</p>' if desc else "", caveat=caveat,
            body=body, source=html.escape(src_rel), prevnext=pn), encoding="utf-8")
        manifest.append({"slug": slug, "title": page_title, "section": section, "desc": desc, "nblm": nblm})

    sections = {}
    for m in manifest:
        sections.setdefault(m["section"], []).append(m)
    idx_body = ""
    for sec, items in sections.items():
        idx_body += f"<h2>{html.escape(sec)}</h2><ul class='pagelist'>" + "".join(
            f'<li><a href="{m["slug"]}.html">{html.escape(m["title"])}</a>' +
            (f' <span class="muted">— {html.escape(m["desc"])}</span>' if m["desc"] else "") + "</li>" for m in items) + "</ul>"
    (LIB / "index.html").write_text(PAGE_TMPL.format(
        title="Library", desc="Every Purview study note rendered as a web page.", section="Index",
        descblock=f'<p class="lead">{len(manifest)} pages rendered from the Obsidian deep-dive pack and the NotebookLM exports.</p>',
        caveat="", body=idx_body, source="Learning/tech-deep-dive/microsoft-purview/", prevnext=""), encoding="utf-8")
    (LIB / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    (LIB / "manifest.js").write_text("window.LIBRARY = " + json.dumps(manifest) + ";\n", encoding="utf-8")
    print(f"built {len(manifest)} pages + index; {len(SOURCES)} sources linked")


if __name__ == "__main__":
    main()
