"""Render the Microsoft Purview vault pack (and NotebookLM exports) into themed HTML pages under library/.

Source of truth stays in Obsidian. Re-run after editing the vault:  python scripts/build_library.py
Writes library/*.html and library/manifest.json (read by index.html's Library view).
"""
import csv
import html
import io
import json
import re
from pathlib import Path

import markdown
import yaml

SITE = Path(__file__).resolve().parent.parent
LIB = SITE / "library"
PACK = Path(r"C:\obsidian\personal_research_2026\Learning\tech-deep-dive\microsoft-purview")
EXP = PACK / "notebooklm" / "exports"
OUT = Path(r"C:\output\obsidian\notebooklm\tdd-microsoft-purview")

NBLM_CAVEAT = (
    "Generated by NotebookLM from the 36-row Microsoft source ledger. The vault views are the source of truth "
    "where they differ. Known corrections: the GCC FedRAMP \"Moderate vs High\" conflict is resolved by [S35] "
    "(Moderate P-ATO plus High equivalency, not a documentation error); the Amazon S3/RDS gap applies to the "
    "Azure Government Data Map [S4], not to the GCC High or DoD Microsoft 365 columns; claims cited only to "
    "\"Video Transcript\" are not in the ledger."
)

# (slug, source path, section, title override or None, nblm?)
PAGES = [
    ("hub", PACK / "00 - Microsoft Purview Hub.md", "Plan", "Microsoft Purview deep dive hub", False),
    ("mission", PACK / "MISSION.md", "Plan", None, False),
    ("intake", PACK / "intake" / "interview-answers.md", "Plan", "Scope interview", False),
    ("intake-record", PACK / "intake" / "2026-09-26 - Intake.md", "Plan", "Intake record", False),
    ("progress-log", PACK / "Progress Log.md", "Plan", "Progress log", False),
    ("day-plan", PACK / "day-plan.md", "Plan", None, False),
    ("mindmap", PACK / "intake" / "mindmap.md", "Plan", "Mind map (scope)", False),
    ("view-01-conceptual", PACK / "views" / "01 - Conceptual View.md", "Architecture views", None, False),
    ("view-02-logical", PACK / "views" / "02 - Logical View.md", "Architecture views", None, False),
    ("view-03-physical", PACK / "views" / "03 - Physical View.md", "Architecture views", None, False),
    ("view-04-integration-ai", PACK / "views" / "04 - Integration and AI Elements.md", "Architecture views", None, False),
    ("diagram-index", PACK / "assets" / "diagrams" / "00 - Diagram Index.md", "Architecture views", "Diagram index", False),
    ("diagram-sources", PACK / "assets" / "diagrams", "Architecture views", "Diagram sources (draw.io and Mermaid)", False),
    *[(f"block-{p.stem}", p, "Day blocks", None, False) for p in sorted((PACK / "blocks").glob("*.md"))],
    ("glossary", PACK / "GLOSSARY.md", "Reference", None, False),
    ("cheatsheet", PACK / "reference" / "cheatsheet.md", "Reference", None, False),
    ("quiz-bank", PACK / "reference" / "quiz-bank.md", "Reference", None, False),
    ("source-ledger", PACK / "reference" / "source-ledger.md", "Reference", None, False),
    ("resources", PACK / "RESOURCES.md", "Reference", None, False),
    ("prompt-library", PACK / "prompts" / "00 - Prompt Library.md", "Prompts", None, False),
    ("prompts-all", PACK / "prompts" / "notebooklm-all-prompts.md", "Prompts", "All NotebookLM prompts (archive)", False),
    ("prompts-tailored", PACK / "prompts" / "tailored-prompts.md", "Prompts", None, False),
    ("prompts-notebooklm-set", PACK / "prompts" / "notebooklm-prompt-set.md", "Prompts", None, False),
    ("prompts-decision-packet", PACK / "prompts" / "notebooklm-room-craft-decision-packet.md", "Prompts", None, False),
    ("prompts-glossary-gap", PACK / "prompts" / "glossary-gap-prompts.md", "Prompts", "Glossary gap prompts", False),
    ("prompts-deep-dive-extra", PACK / "prompts" / "deep-dive-extra-prompts.md", "Prompts", None, False),
    ("nblm-briefing", EXP / "Comprehensive Briefing Document_ Microsoft Purview Architecture, Security Contro.md", "NotebookLM reports", "Briefing document", True),
    ("nblm-study-guide", EXP / "Microsoft Purview Technical Study Guide.md", "NotebookLM reports", "Technical study guide", True),
    ("nblm-conceptual", EXP / "Conceptual Architecture View_ Enterprise Data Security, Governance, and AI Prote.md", "NotebookLM reports", "Conceptual architecture view (report)", True),
    ("nblm-logical", EXP / "Logical Architecture View_ Microsoft Purview.md", "NotebookLM reports", "Logical architecture view (report)", True),
    ("nblm-physical", EXP / "Physical Architecture View_ Microsoft Purview Infrastructure, Runtimes, and Clou.md", "NotebookLM reports", "Physical architecture view (report)", True),
    ("nblm-ai-report", EXP / "Technical Report_ Microsoft Purview AI Capabilities, Governance Architecture, an.md", "NotebookLM reports", "AI capabilities technical report", True),
    ("nblm-third-party", EXP / "Catalog of Third-Party and External System Integrations for Microsoft Purview.md", "NotebookLM reports", "Third-party integration catalog", True),
    ("nblm-failure-modes", EXP / "Comprehensive Failure Mode and Security Weakness Catalog for Microsoft Purview D.md", "NotebookLM reports", "Failure mode and security weakness catalog", True),
    ("nblm-crosswalk", EXP / "MICROSOFT PURVIEW ARCHITECTURAL CROSSWALK_ TOGAF ADM, DoDAF VIEWPOINTS, AND ABST.md", "NotebookLM reports", "TOGAF / DoDAF crosswalk", True),
    ("nblm-decision-packet", EXP / "Executive Decision Packet_ Microsoft Purview Architecture & Investment Strategy.md", "NotebookLM reports", "Executive decision packet", True),
    ("nblm-gap-table", EXP / "Glossary Gap Data Table.md", "NotebookLM study sets", "Glossary gap data table", True),
    ("nblm-gap-quiz", EXP / "Glossary Gap Quiz.md", "NotebookLM study sets", "Glossary gap quiz (platform edges)", True),
    ("nblm-gap-cards", EXP / "Glossary Gap Flashcards.md", "NotebookLM study sets", "Glossary gap flashcards", True),
    ("nblm-general-quiz", EXP / "General Quiz.md", "NotebookLM study sets", "General quiz", True),
    ("nblm-general-cards", EXP / "General Flashcards.md", "NotebookLM study sets", "General flashcards", True),
    ("media-deep-dive-cut", PACK / "Deep Dive Cut.md", "Media", "Deep dive cut", False),
    ("media-cut-script", PACK / "video" / "cut-script.json", "Media", "Deep dive cut script (narration and question cards)", False),
    ("media-slides", PACK / "Presentation slides.md", "Media", "Presentation slides", False),
    ("media-shorts-plan", PACK / "prompts" / "shorts-topics.json", "Media", "Shorts plan", False),
    ("pipeline-suite", PACK / "notebooklm" / "00 - Suite.md", "Pipeline", "NotebookLM suite", False),
    ("pipeline-inventory", PACK / "notebooklm" / "01 - Download Inventory.md", "Pipeline", "NotebookLM download inventory", False),
    ("pipeline-run-record", OUT / "tdd-microsoft-purview__2026-09-26__notebooklm.json", "Pipeline", "NotebookLM run record", False),
    ("pipeline-operator", PACK / "scripts" / "OPERATOR-COMMANDS.md", "Pipeline", "Operator commands", False),
    ("pipeline-runner", PACK / "scripts" / "notebooklm_w8_tdd-microsoft-purview.ps1", "Pipeline", "NotebookLM W8 runner script", False),
    *[(f"source-{p.stem}", p, "NotebookLM source bundle", f"Source as uploaded: {p.stem}", False) for p in sorted((OUT / "sources").glob("*.md"))],
    ("nblm-key-claims", EXP / "Key Claims and Architectural Implications of Microsoft Purview.csv", "NotebookLM reports", "Key claims and architectural implications", True),
    ("nblm-mindmap", EXP / "Microsoft Purview Architecture.json", "NotebookLM reports", "NotebookLM mind map", True),
]


# Vault notes whose content lives on a console view rather than a library page.
CONSOLE_LINKS = {"Deep Dive Cut": "deck", "Presentation slides": "deck", "shorts-topics": "shorts"}


def load_sources():
    rows = {}
    text = (PACK / "reference" / "source-ledger.md").read_text(encoding="utf-8")
    for m in re.finditer(r"^\|\s*(\d+)\s*\|\s*([^|]+?)\s*\|\s*(https?://\S+?)\s*\|", text, re.M):
        rows[int(m.group(1))] = (m.group(2), m.group(3))
    return rows


SOURCES = load_sources()


def split_frontmatter(text):
    text = text.lstrip("\ufeff")
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            try:
                fm = yaml.safe_load(text[3:end]) or {}
            except yaml.YAMLError:
                fm = {}
            return fm, text[end + 4:]
    return {}, text


def slug_for_target(target):
    t = target.split("|")[0].split("#")[0].strip().replace("\\", "/")
    name = t.rsplit("/", 1)[-1].removesuffix(".md")
    for slug, path, *_ in PAGES:
        if path.stem == name:
            return slug
    return None


def convert_obsidian(md):
    md = re.sub(r"\$\[(S[^\]]+)\]\$", r"[\1]", md)  # NotebookLM $[S1]$ citations

    def embed(m):
        target = m.group(1).split("|")[0].strip()
        if target.lower().endswith((".png", ".jpg", ".jpeg", ".gif", ".svg")):
            name = target.rsplit("/", 1)[-1]
            sub = "diagrams" if "diagrams" in target else "slides"
            m_sl = re.fullmatch(r"(?i)slide(\d+)\.jpe?g", name)
            if m_sl:
                name = f"slide-{int(m_sl.group(1)):02d}.jpg"
            return f'<a href="../assets/{sub}/{name}" target="_blank"><img class="embed" src="../assets/{sub}/{name}" alt="{html.escape(name)}"></a>'
        return ""
    md = re.sub(r"!\[\[([^\]]+)\]\]", embed, md)

    def wikilink(m):
        inner = m.group(1).replace("\\|", "|")
        label = inner.split("|", 1)[1] if "|" in inner else inner.split("/")[-1].removesuffix(".md")
        slug = slug_for_target(inner)
        if slug:
            return f"[{label}]({slug}.html)"
        stem = inner.split("|")[0].split("/")[-1].removesuffix(".md")
        if stem in CONSOLE_LINKS:
            return f"[{label}](../index.html#/{CONSOLE_LINKS[stem]})"
        return f"*{label}*"
    md = re.sub(r"\[\[([^\]]+)\]\]", wikilink, md)

    # Obsidian callouts -> html blocks
    out, lines, i = [], md.split("\n"), 0
    while i < len(lines):
        m = re.match(r"^>\s*\[!(\w+)\]([-+]?)\s*(.*)$", lines[i])
        if m:
            kind, title = m.group(1).lower(), m.group(3) or m.group(1).title()
            body = []
            i += 1
            while i < len(lines) and lines[i].startswith(">"):
                body.append(re.sub(r"^>\s?", "", lines[i]))
                i += 1
            inner = markdown.markdown("\n".join(body), extensions=["tables", "fenced_code", "sane_lists"])
            out.append(f'<div class="callout {kind}" markdown="0"><div class="callout-title">{html.escape(title)}</div>{inner}</div>\n')
            continue
        out.append(lines[i])
        i += 1
    return "\n".join(out)


def link_citations(h):
    def one(sid):
        n = int(sid[1:])
        if n in SOURCES:
            t, u = SOURCES[n]
            return f'<a class="cite" href="{html.escape(u)}" target="_blank" rel="noopener" title="{html.escape(t)}">{sid}</a>'
        return sid

    def repl(m):
        parts = re.split(r"(\s*,\s*)", m.group(1))
        return "[" + "".join(one(p) if re.fullmatch(r"S\d+", p) else p for p in parts) + "]"
    return re.sub(r"\[((?:S\d+)(?:\s*,\s*S\d+)*)\]", repl, h)


def render_md(text):
    fm, body = split_frontmatter(text)
    body = re.sub(r"^\*\*Location:\*\*.*$", "", body, flags=re.M)
    body = convert_obsidian(body)
    body = re.sub(r"```mermaid\n(.*?)```", lambda m: f'<pre class="mermaid">{html.escape(m.group(1))}</pre>', body, flags=re.S)
    h = markdown.markdown(body, extensions=["tables", "fenced_code", "sane_lists", "md_in_html"])
    h = re.sub(r"<li>\[ \]", '<li class="task"><input type="checkbox" disabled>', h)
    h = re.sub(r"<li>\[x\]", '<li class="task"><input type="checkbox" checked disabled>', h)
    return fm, link_citations(h)


def render_csv(text):
    rows = list(csv.reader(io.StringIO(text.lstrip("\ufeff"))))
    head, body = rows[0], rows[1:]
    t = "<table><thead><tr>" + "".join(f"<th>{html.escape(c)}</th>" for c in head) + "</tr></thead><tbody>"
    for r in body:
        t += "<tr>" + "".join(f"<td>{html.escape(c)}</td>" for c in r) + "</tr>"
    return {}, t + "</tbody></table>"


def render_mindmap_json(text):
    data = json.loads(text.lstrip("\ufeff"))

    def node(n):
        name = html.escape(n.get("name") or n.get("title") or n.get("text") or "")
        kids = n.get("children") or []
        return f"<li>{name}" + (("<ul>" + "".join(node(k) for k in kids) + "</ul>") if kids else "") + "</li>"
    roots = data if isinstance(data, list) else [data]
    return {}, '<ul class="tree">' + "".join(node(r) for r in roots) + "</ul>"


def render_cut_script(text):
    d = json.loads(text)
    cards, labels = d.get("cards", []), d.get("labels", [])
    h = f"<p><b>Opening.</b> {html.escape(d.get('open', ''))}</p>"
    for i, line in enumerate(d.get("slides", []), 1):
        n = f"{i:02d}"
        label = labels[i - 1] if i - 1 < len(labels) else ""
        h += f"<h2>Slide {i}: {html.escape(label)}</h2>"
        c = cards[i - 2] if 2 <= i and i - 2 < len(cards) else None
        if c:
            h += (f'<div class="callout question"><div class="callout-title">Question card: {html.escape(c["question"])}</div>'
                  f'<p><b>{html.escape(c["detail"])}</b> {html.escape(c["why"])}</p><p><i>Example:</i> {html.escape(c["example"])}</p></div>')
        h += f'<a href="../assets/slides/slide-{n}.jpg" target="_blank"><img class="embed" src="../assets/slides/slide-{n}.jpg" alt="Slide {i}" loading="lazy"></a>'
        h += f"<p>{html.escape(line)}</p>"
        flag = (d.get("unverified_on_slides") or {}).get(str(i))
        if flag:
            h += f'<div class="callout warning"><div class="callout-title">Grounding check</div><p>{html.escape(flag)}</p></div>'
    h += f"<h2>Recap</h2><p>{html.escape(d.get('recap', ''))}</p><h2>Close</h2><p>{html.escape(d.get('close', ''))}</p>"
    h += '<p>Watch the cut on the <a href="../index.html#/deck">Deck and deep-dive cut</a> page.</p>'
    return {"description": "Every narration line and question card from the deep-dive cut, with the slide it belongs to."}, h


def render_shorts_plan(text):
    plan = json.loads(text)
    site = json.loads((SITE / "shorts-catalog.json").read_text(encoding="utf-8"))
    mp = EXP / "shorts-manifest.json"
    made = json.loads(mp.read_text(encoding="utf-8-sig")) if mp.exists() else []
    ids = {m.get("name"): m.get("artifact_id", "") for m in made}
    h = f"<p>{html.escape(plan.get('note', ''))}</p><h2>Planned shorts (NotebookLM prompts)</h2>"
    h += "<table><thead><tr><th>#</th><th>Planned title</th><th>One job (prompt focus)</th><th>NotebookLM artifact</th></tr></thead><tbody>"
    for i, it in enumerate(plan.get("items", []), 1):
        h += f"<tr><td>{i}</td><td>{html.escape(it['title'])}</td><td>{html.escape(it['focus'])}</td><td><code>{html.escape(ids.get(it['name'], ''))}</code></td></tr>"
    h += "</tbody></table><h2>Published shorts</h2><p>NotebookLM titled the finished videos itself, so they do not map one-to-one to the planned titles.</p>"
    h += "<table><thead><tr><th>Short</th><th>Family</th><th>Length</th><th>Watch</th></tr></thead><tbody>"
    for it in site.get("items", []):
        yt = it.get("youtube")
        link = f'<a href="https://www.youtube.com/shorts/{yt}" target="_blank" rel="noopener">YouTube</a> · ' if yt else ""
        h += f"<tr><td>{html.escape(it['title'])}</td><td>{html.escape(it.get('pillar', ''))}</td><td>{it.get('duration', '')} s</td><td>{link}<a href=\"../index.html#/shorts/{it['id']}\">On the site</a></td></tr>"
    h += "</tbody></table>"
    dd = site.get("deep_dive", {})
    if dd.get("youtube"):
        h += f'<p>Long form: <a href="https://www.youtube.com/watch?v={dd["youtube"]}" target="_blank" rel="noopener">deep-dive cut on YouTube</a>.</p>'
    return {"description": "The six planned shorts with their one-job prompts, and the published videos."}, h


def render_json_record(text):
    d = json.loads(text)

    def row(k, v):
        v = "<pre>" + html.escape(json.dumps(v, indent=2, ensure_ascii=False)) + "</pre>" if isinstance(v, (dict, list)) else html.escape(str(v))
        return f"<tr><th>{html.escape(str(k))}</th><td>{v}</td></tr>"
    body = "<table><tbody>" + "".join(row(k, v) for k, v in d.items()) + "</tbody></table>"
    return {"description": "Machine-readable record of the NotebookLM W8 run for this pack."}, body


def render_code(text):
    return {"description": "The script that ran the NotebookLM W8 suite for this pack."}, f"<pre><code>{html.escape(text)}</code></pre>"


def render_diagram_sources(folder):
    h = "<p>Each diagram as the rendered PNG, the editable draw.io file, and the Mermaid source where one exists. Open .drawio files in draw.io (desktop, or app.diagrams.net).</p>"
    for png in sorted(folder.glob("*.png")):
        stem = png.stem
        links = [f'<a href="../assets/diagrams/{png.name}" target="_blank">PNG</a>']
        if (folder / f"{stem}.drawio").exists():
            links.append(f'<a href="../assets/diagrams/{stem}.drawio" download>draw.io</a>')
        mmd = folder / f"{stem}.mmd"
        if mmd.exists():
            links.append(f'<a href="../assets/diagrams/{stem}.mmd" download>Mermaid (.mmd)</a>')
        h += f"<h2>{html.escape(stem)}</h2><p>{' · '.join(links)}</p>"
        h += f'<a href="../assets/diagrams/{png.name}" target="_blank"><img class="embed" src="../assets/diagrams/{png.name}" alt="{html.escape(stem)}" loading="lazy"></a>'
        if mmd.exists():
            src = html.escape(mmd.read_text(encoding="utf-8"))
            h += f'<details><summary>Mermaid source</summary><pre>{src}</pre></details>'
    return {"description": "Rendered diagrams with their editable draw.io and Mermaid sources."}, h


PAGE_TMPL = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title} | Learn Purview</title>
<meta name="description" content="{desc}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="library.css">
<script>try{{var p=JSON.parse(localStorage.getItem("appPalette"))||"github",m=JSON.parse(localStorage.getItem("appMode"))||"dark";document.documentElement.setAttribute("data-theme",p+"-"+m);}}catch(e){{document.documentElement.setAttribute("data-theme","github-dark");}}</script>
</head>
<body>
<header class="topbar">
  <a href="../index.html" class="home">&larr; Learn Purview console</a>
  <span class="crumb">Library · {section}</span>
  <a href="index.html" class="home">All pages</a>
</header>
<main class="doc">
  <div class="kicker">{section}</div>
  <h1 class="doctitle">{title}</h1>
  {descblock}
  {caveat}
  <article>{body}</article>
  <footer class="docfoot">
    Rendered from <code>{source}</code>. The Obsidian vault is the source of truth. Study material only. Citations <span class="cite">S#</span> link to the Microsoft source ledger.
    {prevnext}
  </footer>
</main>
<script type="module">
import mermaid from "https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs";
const dark=(document.documentElement.getAttribute("data-theme")||"").endsWith("dark");
mermaid.initialize({{startOnLoad:true,theme:dark?"dark":"default",securityLevel:"strict"}});
</script>
</body>
</html>
"""


def main():
    LIB.mkdir(exist_ok=True)
    manifest = []
    for idx, (slug, path, section, title, nblm) in enumerate(PAGES):
        if path.is_dir():
            fm, body = render_diagram_sources(path)
        else:
            text = path.read_text(encoding="utf-8-sig")
            if path.suffix == ".csv":
                fm, body = render_csv(text)
            elif path.name == "cut-script.json":
                fm, body = render_cut_script(text)
            elif path.name == "shorts-topics.json":
                fm, body = render_shorts_plan(text)
            elif path.name.endswith("__notebooklm.json"):
                fm, body = render_json_record(text)
            elif path.suffix == ".json":
                fm, body = render_mindmap_json(text)
            elif path.suffix == ".ps1":
                fm, body = render_code(text)
            else:
                fm, body = render_md(text)
        h1 = re.search(r"<h1>(.*?)</h1>", body)
        page_title = title or (re.sub("<.*?>", "", h1.group(1)) if h1 else path.stem)
        if h1 and not title:
            body = body.replace(h1.group(0), "", 1)
        desc = str(fm.get("description", "")) if fm else ""
        caveat = f'<div class="callout warning"><div class="callout-title">NotebookLM output — read with the vault views</div><p>{link_citations(html.escape(NBLM_CAVEAT))}</p></div>' if nblm else ""
        prev_ = PAGES[idx - 1] if idx > 0 and PAGES[idx - 1][2] == section else None
        next_ = PAGES[idx + 1] if idx + 1 < len(PAGES) and PAGES[idx + 1][2] == section else None
        pn = ""
        if prev_ or next_:
            pn = '<div class="prevnext">' + (f'<a href="{prev_[0]}.html">&larr; Previous</a>' if prev_ else "<span></span>") + \
                 (f'<a href="{next_[0]}.html">Next &rarr;</a>' if next_ else "<span></span>") + "</div>"
        src_rel = str(path.relative_to(PACK.parent.parent.parent)) if PACK.parent.parent.parent in path.parents else str(path)
        (LIB / f"{slug}.html").write_text(PAGE_TMPL.format(
            title=html.escape(page_title), desc=html.escape(desc), section=html.escape(section),
            descblock=f'<p class="lead">{html.escape(desc)}</p>' if desc else "", caveat=caveat,
            body=body, source=html.escape(src_rel), prevnext=pn), encoding="utf-8")
        manifest.append({"slug": slug, "title": page_title, "section": section, "desc": desc, "nblm": nblm})

    sections = {}
    for m in manifest:
        sections.setdefault(m["section"], []).append(m)
    idx_body = ""
    for sec, items in sections.items():
        idx_body += f"<h2>{html.escape(sec)}</h2><ul class='pagelist'>" + "".join(
            f'<li><a href="{m["slug"]}.html">{html.escape(m["title"])}</a>' +
            (f' <span class="muted">— {html.escape(m["desc"])}</span>' if m["desc"] else "") + "</li>" for m in items) + "</ul>"
    (LIB / "index.html").write_text(PAGE_TMPL.format(
        title="Library", desc="Every Purview study note rendered as a web page.", section="Index",
        descblock=f'<p class="lead">{len(manifest)} pages rendered from the Obsidian deep-dive pack and the NotebookLM exports.</p>',
        caveat="", body=idx_body, source="Learning/tech-deep-dive/microsoft-purview/", prevnext=""), encoding="utf-8")
    (LIB / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    (LIB / "manifest.js").write_text("window.LIBRARY = " + json.dumps(manifest) + ";\n", encoding="utf-8")
    print(f"built {len(manifest)} pages + index; {len(SOURCES)} sources linked")


if __name__ == "__main__":
    main()
